### ISSUE TITLE
icon doesn't appear on bar

### ISSUE THREAD

**Issue by l4n1skyy** [unode/polypomo#10] opened 2023-07-11 02:17 UTC
![image](https://github.com/unode/polypomo/assets/71810630/57d6067c-bdd4-43d3-86e6-cc43bfee7be2)
![image1](https://github.com/unode/polypomo/assets/71810630/57732aa3-ea32-4ea5-9bb9-76262ee99466)
![image](https://github.com/unode/polypomo/assets/71810630/2f0e7bef-b1eb-4796-8aef-508189d9e373)
i have installed noto and done the troubleshooting steps

**Comment by unode** [comment] 2023-07-12 13:04
On my system:

```
font-0 = fixed:pixelsize=10;1
font-1 = Noto Emoji:scale=15:antialias=false;0
```
works fine,

But you may also want to try installing the `siji` font.

My full polybar font configuration:
```
font-0 = fixed:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = siji:pixelsize=10;1
font-3 = Noto Emoji:scale=15:antialias=false;0
```

Note you need `Noto Emoji` not simply `Noto`. [Emoji is a sub-font](https://fonts.google.com/noto/specimen/Noto+Emoji) of the Noto family..

**Comment by l4n1skyy** [comment] 2023-07-13 01:26
![image](https://github.com/unode/polypomo/assets/71810630/98f79776-baca-4087-b110-0b59bbf6c2c9)
![image](https://github.com/unode/polypomo/assets/71810630/fbecc4c1-ab18-44fb-a581-dddf5d0ca28e)
![image](https://github.com/unode/polypomo/assets/71810630/5fdb832c-db41-4bbd-96c3-3193fbe50fb9)
I've installed siji, but for some reason it still uses the noto emojij icon :') thanks for replying btw, I'm really grateful for your help!

**Comment by l4n1skyy** [comment] 2023-07-13 01:32
![image](https://github.com/unode/polypomo/assets/71810630/bf4bc968-7628-41e9-ba32-763748c34571)
-----
![image](https://github.com/unode/polypomo/assets/71810630/78e4b204-e962-4205-b043-449f53e69760)
![image](https://github.com/unode/polypomo/assets/71810630/6489dacc-ae6a-4fa6-8091-179f53b05f82)
![image](https://github.com/unode/polypomo/assets/71810630/31ab688b-45bd-4655-abe5-a7e92315d1cf)
Thanks a lot for replying, I really appreciate it!! Unfortunately only noto loads now.. not sure where I'm going wrong

**Comment by unode** [comment] 2023-07-14 09:21
Font settings should go under `[bar/main]`.

Can you try removing font settings from other components or even reduce the polybar configuration to a minimum?

I'm afraid this is less a polypomo issue and more of a polybar one. Font rendering is... complicated.

In your screenshots, I see that the Noto Emoji glyphs are rendering. I'm not sure I see what the issue is now. It looks fixed to me.
If the problem is which fonts gets loaded, that's beyond polypomo.

**Comment by unode** [comment] 2023-07-14 09:30
For font rendering issues, you may want to read https://wiki.archlinux.org/title/font_configuration#Alias
The [`Alias`](https://wiki.archlinux.org/title/font_configuration#Alias) section may provide some help.

**Comment by unode** [comment] 2023-07-21 15:29
Closing as not a polypomo bug.

**Closed as completed by unode** 2023-07-21 15:29 UTC
Labels: invalid, question
